apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpserver
spec:
  selector:
    matchLabels:
      app: httpserver
  replicas: 1
  template:
    metadata:
      labels:
        app: httpserver
    spec:
      containers:
        - name: httpserver
          image: toffguy77/k8sInAction:$GITHUB_SHA
          ports:
            - containerPort: 8080
