apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpserver
spec:
  selector:
    matchLabels:
      app: httpserver
  replicas: 1
  template:
    metadata:
      labels:
        app: httpserver
    spec:
      containers:
        - name: httpserver
          image: 'ghcr.io/toffguy77/k8sinaction:sha-d1e10e1'
          ports:
            - containerPort: 8080
